apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "test-svc.fullname" . }}-job
  labels:
    app: {{ include "test-svc.name" . }}
    chart: {{ include "test-svc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ include "test-svc.name" . }}
        chart: {{ include "test-svc.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ include "test-svc.fullname" . }}-container
        image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
        imagePullPolicy: {{ .Values.job.image.pullPolicy }}
      restartPolicy: OnFailure
