apiVersion: v1
kind: Service
metadata:
  name: {{ include "position-simulator.fullname" . }}-fleetman-position-tracker
  labels:
  {{- include "position-simulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fleetmanPositionTracker.type }}
  selector:
    app: position-tracker
    {{- include "position-simulator.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.fleetmanPositionTracker.ports | toYaml | nindent 2 }}